name: autogis

channels:
  - conda-forge

dependencies:
  - python=3.8
  - matplotlib
  - geopandas
  - geojson
  - pysal
  - mapclassify
  - osmnx
  - nose
  - pyrosm
  - geopy
  - geojson
  - rasterio
  - contextily
  - folium
  - mplleaflet
  - bokeh
  - xlrd
  - jupyterlab 
  - jupyterlab-git 
