name: autogis

channels:
  - conda-forge
  - patrikhlobi

dependencies:
  - python=3.8
  - matplotlib
  - geopandas
  - geojson
  - pysal
  - mapclassify
  - osmnx
  - nose
  - pyrosm
  - geopy
  - geojson
  - rasterio
  - contextily
  - folium
  - mplleaflet
  - pandas-bokeh
  - bokeh
  - xlrd
  - jupyterlab 
  - jupyterlab-git 
